// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (openbsd && amd64) || (openbsd && arm64) || (windows && (amd64 || arm64))

package libsqlite3

const __PIC__ = 1

const __pic__ = 1
