// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (netbsd && amd64) || (openbsd && amd64) || (openbsd && arm64)

package libsqlite3

const __const = 0

const __signed = 0
