// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm64) || (netbsd && amd64)

package libsqlite3

type Tbintime = struct {
	Fsec  Ttime_t
	Ffrac Tuint64_t
}
