// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

type Ttimespec = struct {
	Ftv_sec  Ttime_t
	Ftv_nsec int32
}
