// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && arm) || (linux && arm64) || (linux && ppc64le)

package libsqlite3

const O_DIRECTORY = 16384

const O_NOFOLLOW = 32768

const O_TMPFILE = 4210688
