// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (windows && 386)

package libsqlite3

const __SIZEOF_FLOAT80__ = 12

const __code_model_32__ = 1
