// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && arm) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

const __GXX_TYPEINFO_EQUALITY_INLINE = 0
