// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && arm) || (linux && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

const __WCHAR_MIN__ = 0
