// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (freebsd && arm64) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (openbsd && arm64)

package libsqlite3

const __FP_FAST_FMA = 1

const __FP_FAST_FMAF = 1
