// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (freebsd && 386) || (freebsd && amd64) || (openbsd && amd64)

package libsqlite3

const __BITINT_MAXWIDTH__ = 8388608

const __NO_MATH_INLINES = 1
