// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && ppc64le) || (openbsd && amd64) || (openbsd && arm64)

package libsqlite3

const __LITTLE_ENDIAN__ = 1
