// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (linux && ppc64le) || (linux && s390x)

package libsqlite3

const FP_FAST_FMAL = 1
