// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (netbsd && amd64)

package libsqlite3

const AT_SYMLINK_FOLLOW = 1024

const POSIX_FADV_NORMAL = 0

const POSIX_FADV_RANDOM = 1

const POSIX_FADV_SEQUENTIAL = 2

const POSIX_FADV_WILLNEED = 3

const RTLD_NODELETE = 4096

type Tdev_t = uint64
