// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (linux && arm64) || (linux && loong64) || (linux && riscv64)

package libsqlite3

const FIOQSIZE = 21600
