// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && arm) || (netbsd && amd64) || (openbsd && amd64) || (openbsd && arm64)

package libsqlite3

type t__fd_mask = uint32
