// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

const __DECIMAL_BID_FORMAT__ = 1
