// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (linux && ppc64le) || (openbsd && amd64)

package libsqlite3

const __FLOAT128__ = 1
