// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && arm) || (freebsd && arm64) || (linux && arm) || (linux && arm64)

package libsqlite3

type Twchar_t = uint32

const __WCHAR_MAX__ = 4294967295

type t__predefined_wchar_t = uint32
