// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && arm64) || (linux && arm64) || (linux && ppc64le) || (linux && s390x) || (openbsd && arm64)

package libsqlite3

const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 = 1
