// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && arm) || (freebsd && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

const WCHAR_MIN = 0
