// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && arm) || (linux && 386) || (windows && 386)

package libsqlite3

const _ILP32 = 1

const __ILP32__ = 1
