// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && arm) || (netbsd && amd64)

package libsqlite3

type Tclock_t = uint32
