// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

const __FLT_EVAL_METHOD_TS_18661_3__ = 2

const __FLT_EVAL_METHOD__ = 2
