// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

type Toff64_t = int64
