// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (windows && 386)

package libsqlite3

const __USER_LABEL_PREFIX__ = 0
