// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && amd64) || (freebsd && arm64) || (openbsd && amd64) || (openbsd && arm64)

package libsqlite3

type Ttm = struct {
	Ftm_sec    int32
	Ftm_min    int32
	Ftm_hour   int32
	Ftm_mday   int32
	Ftm_mon    int32
	Ftm_year   int32
	Ftm_wday   int32
	Ftm_yday   int32
	Ftm_isdst  int32
	Ftm_gmtoff int64
	Ftm_zone   uintptr
}

/*
** The MSVC CRT on Windows CE may not have a localtime() function.
** So declare a substitute.  The substitute function itself is
** defined in "os_win.c".
 */

const __INT_FAST64_FMTd__ = "ld"

const __INT_FAST64_FMTi__ = "li"

const __INT_LEAST64_FMTd__ = "ld"

const __INT_LEAST64_FMTi__ = "li"

const __UINT_FAST64_FMTX__ = "lX"

const __UINT_FAST64_FMTo__ = "lo"

const __UINT_FAST64_FMTu__ = "lu"

const __UINT_FAST64_FMTx__ = "lx"

const __UINT_LEAST64_FMTX__ = "lX"

const __UINT_LEAST64_FMTo__ = "lo"

const __UINT_LEAST64_FMTu__ = "lu"

const __UINT_LEAST64_FMTx__ = "lx"

type t__key_t = int64

type t__ptrdiff_t = int64

type t__size_t = uint64

type t__ssize_t = int64

type t__suseconds_t = int64
