// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (freebsd && arm) || (freebsd && arm64) || (openbsd && arm64)

package libsqlite3

const __ARM_FEATURE_LDREX = 15

const __BITINT_MAXWIDTH__ = 128
