// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

type Terrno_t = int32

type Tmode_t = uint16

const stderr = 0

const stdin = 0

const stdout = 0
