// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && arm) || (freebsd && arm64) || (openbsd && arm64)

package libsqlite3

const __ARM_ACLE = 200
