// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (freebsd && arm) || (linux && arm) || (linux && s390x)

package libsqlite3

const __BIGGEST_ALIGNMENT__ = 8
