// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (linux && arm) || (linux && riscv64)

package libsqlite3

const __GCC_ATOMIC_BOOL_LOCK_FREE = 1

const __GCC_ATOMIC_CHAR16_T_LOCK_FREE = 1

const __GCC_ATOMIC_CHAR_LOCK_FREE = 1

const __GCC_ATOMIC_SHORT_LOCK_FREE = 1
