// Code generated by modernc.org/undup from the per-target ccgo_*.go files; DO NOT EDIT.

//go:build (freebsd && amd64) || (freebsd && arm64) || (linux && 386) || (linux && arm) || (windows && (amd64 || arm64)) || (windows && 386)

package libsqlite3

type Tclock_t = int32
